version: '3'

services:
  app:
    ports:
      - "${SERVER_HOST:-127.0.0.1}:${SERVER_PORT:-8080}:8080"
    build:
      context: .
      dockerfile: ./dev.dockerfile
    volumes:
      - ./:/app
    environment:
      - GOYAVE_ENV=docker
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: goyave
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:35432:5432"